In [ ]:
## Seriese in pandas
## Atomatic index taken
import pandas as pd
data =[1,2,3,4,5,6]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [5]:
## seriese from dictionary
data={'a':1,'b':2,'c':3}
seriese_dict=pd.Series(data)
print(seriese_dict)

a    1
b    2
c    3
dtype: int64

In [12]:
## we can give index by ourself
data=[1,2,3,4,5,6]
index=['a','b','c','d','e','f']
seriese=pd.Series(data=data,index=index)
print(seriese)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [16]:
##DataFrame in pandas
data={
    'Name':['Amit','Ashish','jack','john'],
    'Age':[20,21,22,23],
    'City':['Bangalore','New York','Bijing','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0    Amit   20  Bangalore
1  Ashish   21   New York
2    jack   22     Bijing
3    john   23    Florida
<class 'pandas.DataFrame'>

In [ ]:
## We can store in list
import numpy as np
data={
    'Name':['Amit','Ashish','jack','john'],
    'Age':[20,21,22,23],
    'City':['Bangalore','New York','Bijing','Florida']
}
df=pd.DataFrame(data)
print(df)
np.array(df)

     Name  Age       City
0    Amit   20  Bangalore
1  Ashish   21   New York
2    jack   22     Bijing
3    john   23    Florida

array([['Amit', 20, 'Bangalore'],
       ['Ashish', 21, 'New York'],
       ['jack', 22, 'Bijing'],
       ['john', 23, 'Florida']], dtype=object)

In [20]:
## Create a DataFrame from the list of dictionary
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
    
]
index=['i','ii','iii','iv']
df=pd.DataFrame(data=data,index=index)
print(df)

       Name  Age       City
i      Amit   20  Bangalore
ii   Ashish   21   New York
iii    Jack   22     Bijing
iv     John   23    Florida

In [26]:
##Reading data from csv file
import pandas as pd
df=pd.read_csv('customer.csv')
print(df.head(5))## we can use tailto get last 5 data

   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter
1      2  1Ef7b82A4CAAD10    Preston    Lozano
2      3  6F94879bDAfE5a6        Roy     Berry
3      4  5Cef8BFA16c5e3c      Linda     Olsen
4      5  053d585Ab6b3159     Joanna    Bender

                           Company               City  \
0                  Rasmussen Group       East Leonard
1                      Vega-Gentry  East Jimmychester
2                    Murillo-Perry      Isabelborough
3  Dominguez, Mcmillan and Donovan         Bensonview
4         Martin, Lang and Andrade     West Priscilla

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718
1                    Djibouti              5153435776       686-620-1820x944
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947
3          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486

                         Email Subscription Date                      Website
0     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/
1              vmata@colon.com        2021-04-23        http://www.hobbs.com/
2          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/
3  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/
4      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/

In [30]:
##Accessing data by key
data={
    'Name':['Amit','Ashish','jack','john'],
    'Age':[20,21,22,23],
    'City':['Bangalore','New York','Bijing','Florida']
}
df=pd.DataFrame(data)
df['Name']

0      Amit
1    Ashish
2      jack
3      john
Name: Name, dtype: str

In [ ]:
## Accessing data by row index
data={
    'Name':['Amit','Ashish','jack','john'],
    'Age':[20,21,22,23],
    'City':['Bangalore','New York','Bijing','Florida']
}
df=pd.DataFrame(data)
df.loc[0]

Name         Amit
Age            20
City    Bangalore
Name: 0, dtype: object

In [41]:
##Accessing data by coloum index
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df.iloc[0,0]

'Amit'

In [ ]:
## Accessing a specific element using (at)
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
print(df.at[2,'Age'])

22

In [45]:
## Accessing a specific element using(iat)
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
print(df.iat[2,2])

Bijing

In [47]:
## Data manipulation with DataFrame(Baically we add salary section)
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df['Salary']=[50000,60000,70000,80000]
print(df)

     Name  Age       City  Salary
0    Amit   20  Bangalore   50000
1  Ashish   21   New York   60000
2    Jack   22     Bijing   70000
3    John   23    Florida   80000

In [54]:
## Drop a coloum
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df['Salary']=[50000,60000,70000,80000]
print(df)
print(df.drop('Salary',axis=1))

     Name  Age       City  Salary
0    Amit   20  Bangalore   50000
1  Ashish   21   New York   60000
2    Jack   22     Bijing   70000
3    John   23    Florida   80000
     Name  Age       City
0    Amit   20  Bangalore
1  Ashish   21   New York
2    Jack   22     Bijing
3    John   23    Florida

In [ ]:
## Here we see that column not drop permanentally
print(df)

     Name  Age       City  Salary
0    Amit   20  Bangalore   50000
1  Ashish   21   New York   60000
2    Jack   22     Bijing   70000
3    John   23    Florida   80000

In [58]:
##Drop the column permanentally
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df['Salary']=[50000,60000,70000,80000]
print(df)
df.drop('Salary',axis=1,inplace=True)
print(df)

     Name  Age       City  Salary
0    Amit   20  Bangalore   50000
1  Ashish   21   New York   60000
2    Jack   22     Bijing   70000
3    John   23    Florida   80000
     Name  Age       City
0    Amit   20  Bangalore
1  Ashish   21   New York
2    Jack   22     Bijing
3    John   23    Florida

In [59]:
## Here we see that column is permanentally delete
print(df)

     Name  Age       City
0    Amit   20  Bangalore
1  Ashish   21   New York
2    Jack   22     Bijing
3    John   23    Florida

In [60]:
## We can modify the age (integer value)
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df['Age']=df['Age']+1
print(df)

     Name  Age       City
0    Amit   21  Bangalore
1  Ashish   22   New York
2    Jack   23     Bijing
3    John   24    Florida

In [ ]:
## We can drop the row
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df=df.drop(0)##df.drop(0,inplace=True) permanentally delete
print(df)

     Name  Age      City
1  Ashish   21  New York
2    Jack   22    Bijing
3    John   23   Florida

In [66]:
## Data manipulation 
## Handaling missing values
import pandas as pd
df=pd.read_csv('customer1.csv')
df.isnull()
print(df.head(2))

  Series_reference   Period  Data_value  Suppressed STATUS    UNITS  \
0       ECTA.S19A1  2001.03      2462.5         NaN      F  Dollars
1       ECTA.S19A1  2002.03     17177.2         NaN      F  Dollars

   Magnitude                                        Subject  \
0          6  Electronic Card Transactions (ANZSIC06) - ECT
1          6  Electronic Card Transactions (ANZSIC06) - ECT

                                               Group Series_title_1  \
0  Total values - Electronic card transactions A/...         Actual
1  Total values - Electronic card transactions A/...         Actual

         Series_title_2 Series_title_3  Series_title_4  Series_title_5
0  RTS total industries            NaN             NaN             NaN
1  RTS total industries            NaN             NaN             NaN

In [ ]:
## Finding missing data
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
print(df.isnull())

    Name    Age   City
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False

In [69]:
## fill the missing data 
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
print(df.fillna(22))

     Name   Age       City
0    Amit  20.0  Bangalore
1  Ashish  21.0   New York
2    Jack  22.0     Bijing
3    John  23.0    Florida

In [70]:
##If your question is: “Does this column have any missing value?
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
print(df.isnull().any())

Name    False
Age      True
City    False
dtype: bool

In [71]:
##If your question is: “Give me rows with missing values?
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
print(df.isnull().any(axis=1))

0    False
1    False
2     True
3    False
dtype: bool

Here isnull And isna both are same thingh

In [72]:
## We can calculate how many missing values are there
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
print(df.isnull().sum())

Name    0
Age     1
City    0
dtype: int64

In [ ]:
## We can fill the average mean of the age
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df=df.fillna(df['Age'].mean())
print(df)

     Name        Age       City
0    Amit  20.000000  Bangalore
1  Ashish  21.000000   New York
2    Jack  21.333333     Bijing
3    John  23.000000    Florida

In [81]:
## We can change the column name
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df=df.rename(columns={'Name':'name'})
print(df)

     name  Age       City
0    Amit   20  Bangalore
1  Ashish   21   New York
2    Jack   22     Bijing
3    John   23    Florida

In [ ]:
## We can change the index name
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','Age':22,'City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
    
]
index=['i','ii','iii','iv']
df=pd.DataFrame(data=data,index=index)
df=df.rename(index={'i':1})
print(df)

       Name  Age       City
1      Amit   20  Bangalore
ii   Ashish   21   New York
iii    Jack   22     Bijing
iv     John   23    Florida

In [2]:
## We can change the data type
import pandas as pd
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df=df['Age'].fillna(df['Age'].mean()).astype(int)
print(df)

0    20
1    21
2    21
3    23
Name: Age, dtype: int64

In [7]:
## We can multiply the integer part
import pandas as pd
data=[
    {'Name':'Amit','Age':20,'City':'Bangalore'},
    {'Name':'Ashish','Age':21,'City':'New York'},
    {'Name':'Jack','City':'Bijing'},
    {'Name':'John','Age':23,'City':'Florida'}
]
df=pd.DataFrame(data)
df['Age']=df['Age'].fillna(df['Age'].mean()).astype(int)
df['Square_of_age']=df['Age'].apply(lambda x:x**2)
print(df)

     Name  Age       City  Square_of_age
0    Amit   20  Bangalore            400
1  Ashish   21   New York            441
2    Jack   21     Bijing            441
3    John   23    Florida            529

In [ ]:
## We can group the column
df=pd.read_csv('sales_data.csv')
grouped_mean=df.groupby('CONTACTFIRSTNAME')['PRICEEACH'].mean()
print(grouped_mean)

CONTACTFIRSTNAME
Adrian     82.831087
Akiko      82.745000
Allen      82.902917
Ann        84.082308
Anna       83.558043
             ...
Violeta    86.667308
Wendy      79.525833
William    84.998095
Wing C     83.296571
Yoshi      86.172727
Name: PRICEEACH, Length: 72, dtype: float64

In [11]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
##We can group the by two column
df=pd.read_csv('sales_data.csv')
grouped_mean=df.groupby(['CONTACTFIRSTNAME','COUNTRY'])['PRICEEACH'].mean()
print(grouped_mean)

CONTACTFIRSTNAME  COUNTRY
Adrian            Australia    82.831087
Akiko             Japan        82.745000
Allen             USA          82.902917
Ann               UK           84.082308
Anna              Australia    83.558043
                                 ...
Violeta           USA          86.667308
Wendy             Singapore    79.525833
William           USA          84.998095
Wing C            USA          83.296571
Yoshi             Canada       86.172727
Name: PRICEEACH, Length: 77, dtype: float64

In [14]:
## Aggregate multiple function
df=pd.read_csv('sales_data.csv')
grouped_mean=df.groupby(['CONTACTFIRSTNAME','COUNTRY'])['PRICEEACH'].agg(['mean','sum','count'])
print(grouped_mean)

                                 mean      sum  count
CONTACTFIRSTNAME COUNTRY
Adrian           Australia  82.831087  3810.23     46
Akiko            Japan      82.745000  2647.84     32
Allen            USA        82.902917  1989.67     24
Ann              UK         84.082308  2186.14     26
Anna             Australia  83.558043  3843.67     46
...                               ...      ...    ...
Violeta          USA        86.667308  2253.35     26
Wendy            Singapore  79.525833  2862.93     36
William          USA        84.998095  1784.96     21
Wing C           USA        83.296571  2915.38     35
Yoshi            Canada     86.172727  1895.80     22

[77 rows x 3 columns]

In [ ]:
## We can merge and joine two DataFrame(inner)
df1=pd.DataFrame({'key':['A','B','C'],
                  'value1':[1,2,3]
                  })
df2=pd.DataFrame({'key':['A','B','D'],
                  'value2':[4,5,6]
                  })
pd.merge(df1,df2,on="key",how="inner")

  key  value1  value2
0   A       1       4
1   B       2       5

In [17]:
## We can merge and joine two DataFrame(outer)
df1=pd.DataFrame({'key':['A','B','C'],
                  'value1':[1,2,3]
                  })
df2=pd.DataFrame({'key':['A','B','D'],
                  'value2':[4,5,6]
                  })
pd.merge(df1,df2,on="key",how="outer")

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [18]:
## We can merge and joine two DataFrame(right)
df1=pd.DataFrame({'key':['A','B','C'],
                  'value1':[1,2,3]
                  })
df2=pd.DataFrame({'key':['A','B','D'],
                  'value2':[4,5,6]
                  })
pd.merge(df1,df2,on="key",how="right")

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [ ]:
## We can merge and joine two DataFrame(left)
df1=pd.DataFrame({'key':['A','B','C'],
                  'value1':[1,2,3]
                  })
df2=pd.DataFrame({'key':['A','B','D'],
                  'value2':[4,5,6]
                  })
pd.merge(df1,df2,on="key",how="left")

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [ ]:
## We can read the Jason file
import pandas as pd
from io import StringIO
Data='{"Employee_name":"James","Email":"james@gmail.com","job_profile":[{"title1":"Team_leader","title2":"Sr.developer"}]}'
df=pd.read_json(StringIO(Data))
print(df)

  Employee_name            Email  \
0         James  james@gmail.com

                                         job_profile
0  {'title1': 'Team_leader', 'title2': 'Sr.develo...

In [22]:
## Convert DataFrame into json again
df.to_json()

'{"Employee_name":{"0":"James"},"Email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team_leader","title2":"Sr.developer"}}}'

In [23]:
## Convert DataFrame into Json with index
df.to_json(orient='index')

'{"0":{"Employee_name":"James","Email":"james@gmail.com","job_profile":{"title1":"Team_leader","title2":"Sr.developer"}}}'

In [24]:
## Convert DataFrame into Json with same record
df.to_json(orient='records')

'[{"Employee_name":"James","Email":"james@gmail.com","job_profile":{"title1":"Team_leader","title2":"Sr.developer"}}]'

In [ ]:
## We can read the html file with url
url="https://www.fdic.gov/bank-failures/failed-bank-list"
df=pd.read_html(url)
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524